### ISSUE TITLE
Add our 🟢  tools.

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/python-tooling#1]
Here's a list of our 🟢 🚦  from the [webpage](http://github-pages.arc.ucl.ac.uk/python-tooling/).

- [ ] pyinstrument
- [ ] snakeviz
- [ ] asv

- [x] github actions
- [ ] codecov

- [ ] sphinx
- [ ] sphinx-gallery
- [ ] (binder)

- [x] pre-commit
- [x] black
- [x] toml
- [x] isort
- [x] (ruff? autoflake)
- [x] mypy

- [x] build
- [x] setuptools
- [ ] cibuildwheel

- [x] pytest 
- [x] tox
- [x] pytest-cov
- [ ] pytest-mock

- [ ] mamba

**Comment by krishnakumarg1984** [comment]
Some other tools worth considering:

## Linters
- [pydocstyle](https://www.pydocstyle.org/en/stable/): pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.
- [pylama](https://github.com/klen/pylama): Code audit tool for Python.
- [vulture](https://github.com/jendrikseipp/vulture):  Find dead Python code 

## Formatters
- [autoflake](https://github.com/PyCQA/autoflake):  Removes unused imports and unused variables as reported by pyflakes 
- [blue](https://github.com/grantjenks/blue):  The slightly less uncompromising Python code formatter. 
- [reorder-python-imports](https://github.com/asottile/reorder-python-imports):  Rewrites source to reorder python imports 
- [usort](https://github.com/facebook/usort):  Safe, minimal import sorting for Python projects.

**Comment by krishnakumarg1984** [comment]
I just found [pyink](https://github.com/google/pyink), a fork of `black` from Google. @samcunliffe @paddyroddy and others, perhaps worth evaluating during the upcoming python-docathon.

Separate topic, Also found [`pyflyby`](https://github.com/deshaw/pyflyby), a tool that can auto-import missing imports.

**Comment by paddyroddy** [comment]
I'm waiting on astral-sh/ruff#1904, and I'll be ditching `black` forever 😉

**Comment by samcunliffe** [comment]
Going to close this here as, with #319 we've managed most of this. 

I'd argue the remainder are now superseded(?).
