### ISSUE TITLE
Should we add werkzeug to the benchmarking page?

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/python-tooling#102]
* https://pypi.org/project/Werkzeug/

@sfmig you've been using it... which makes you expert. So here's a ticket 😁.

If the answer is "yes": please add it. If "no": please close with `wontfix`.

**Comment by paddyroddy** [comment]
@sfmig this has been open for 18 months!

**Comment by sfmig** [comment]
not sure why I gave thumbs-up, have not used werkzeug before!

I think the benchmarks page is complete enough as is so happy to close.

**Comment by paddyroddy** [comment]
Phew. Thank you @sfmig
