### ISSUE TITLE
Should we separate benchmarking and profiling tools?

### ISSUE THREAD

**Issue by sfmig** [UCL-ARC/python-tooling#104]
The benchmarking section right now includes profiling and benchmarking tools.... should we split them for clarity?

**Comment by dstansby** [comment]
👍 to splitting them

**Comment by samcunliffe** [comment]
There's actually only one benchmarking tool on the benchmarking page. Are there any to add?
Otherwise, we could arguably just rename it to "Profiling".

**Comment by sfmig** [comment]
closed by #266
