### ISSUE TITLE
Should `project_slug` variable be separated in to different variables

### ISSUE THREAD

**Issue by matt-graham** [UCL-ARC/python-tooling#108]
Current the `project_slug` variable is used for lots of different things in the template

  1. The GitHub repository name
  2. The name of the package directory within `src`
  3. The assumed name of the PyPI and Conda distributions

I would personally say these won't all necessarily coincide, particularly 1 and 2/3. I would generally use hyphen separated all lowercase repository names, while the recommendation for Python package names is to use all lowercase without any underscores (or hyphens). I would also generally use a longer more descriptive repository name than I would use for a Python package name. We could potentially split the current `project_slug` variable into separate `project_slug` (or `package_name`) and `repository_name` with the latter defaulting to the value provided for the former to retain the current default behaviour?

**Comment by paddyroddy** [comment]
Interesting question. At the end of the day, users should change the defaults. But it makes sense to suggest something - have no strong views on what that is.

**Comment by matt-graham** [comment]
> At the end of the day, users should change the defaults.

Do you mean specifically here the user should change the defaults for the template variable values when creating an instance of the template, or that users should change the default organization / file naming of the generated project folder after it has been generated? Definitely agree with the former, but for the latter I would say that ideally unless they are doing something unusual users shouldn't need to do too much manual tweaking (beyond actually adding content!), especially if this tweaking is something that could be automated.

On thinking about it further though, I'm not sure if how often it would make sense to have a different repository and package name. Most of the major (scientific) Python packages I can think of have the package and repository names exactly matching. We do have packages we develop in ARC which don't fit this pattern &mdash; for example TLOmodel (repository) versus tlo (package) &mdash; but this is probably not reflective of good practice (specifically in TLOmodel I think its an artefact of using a single repo for various bits of a project rather than having this as a GitHub organization with multiple associated repositories). 

I think the default for `project_slug` could possibly be improved - specifically I'm not sure replacing spaces and underscores in `project_name` with hyphens gives a good model of what this should be as to be a valid package or module name we cannot have hyphens and to align with PEP8 recommendations we shouldn't have underscores in the package name either. But this is a separate issue!

**Comment by matt-graham** [comment]
Closing this as I think on some further reflection I disagree with the premise of my own question 😁.

**Comment by paddyroddy** [comment]
> > At the end of the day, users should change the defaults.
> 
> Do you mean specifically here the user should change the defaults for the template variable values when creating an instance of the template, or that users should change the default organization / file naming of the generated project folder after it has been generated? Definitely agree with the former, but for the latter I would say that ideally unless they are doing something unusual users shouldn't need to do too much manual tweaking (beyond actually adding content!), especially if this tweaking is something that could be automated.
> 
> On thinking about it further though, I'm not sure if how often it would make sense to have a different repository and package name. Most of the major (scientific) Python packages I can think of have the package and repository names exactly matching. We do have packages we develop in ARC which don't fit this pattern — for example TLOmodel (repository) versus tlo (package) — but this is probably not reflective of good practice (specifically in TLOmodel I think its an artefact of using a single repo for various bits of a project rather than having this as a GitHub organization with multiple associated repositories).
> 
> I think the default for `project_slug` could possibly be improved - specifically I'm not sure replacing spaces and underscores in `project_name` with hyphens gives a good model of what this should be as to be a valid package or module name we cannot have hyphens and to align with PEP8 recommendations we shouldn't have underscores in the package name either. But this is a separate issue!

All I mean is, our users shouldn't just be pressing enter and not reading anything. However, I'm sure 99% of the time that is what will happen...
