### ISSUE TITLE
Should we have a badass logo?

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#118]
Consider asking @dstansby whether his partner would be up for this challenge 👀

**Comment by samcunliffe** [comment]
Source material from the lost discussion....

![arc-logo-python-colours](https://github.com/UCL-ARC/python-tooling/assets/1836192/6c53354b-ff87-4d40-8f40-1b9ee9ce6b61)
![Python-logo-notext](https://github.com/UCL-ARC/python-tooling/assets/1836192/3db25288-3f66-4a22-bbf7-4bbd36b0298e)
![ucl-logo](https://github.com/UCL-ARC/python-tooling/assets/1836192/fa851938-5e19-411a-bbc6-04b9ee6917e4)

**Comment by paddyroddy** [comment]
I'm picturing a python wrapped around ARC, eating a cookie?

**Comment by mxochicale** [comment]
Just sketched this one? Any feedback?  
![logo-idea-v00](https://github.com/UCL-ARC/python-tooling/assets/11370681/5344cf30-ab4c-4c6e-bc7d-89a695bf98c5)

**Comment by paddyroddy** [comment]
Let's discuss in Slack

**Comment by mxochicale** [comment]
I think discussions is a suitable place to find some agreement. Just created this one https://github.com/UCL-ARC/python-tooling/discussions/133

**Comment by paddyroddy** [comment]
FYI you can convert an issue to a discussion
<img width="212" alt="image" src="https://github.com/UCL-ARC/python-tooling/assets/15052188/4f4658b0-6196-46bb-a4e6-cc2ac3e79269">
