### ISSUE TITLE
Weird pages-build-deployment failure.

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/python-tooling#125]
Something strange is going on.
[This is failing](https://github.com/UCL-ARC/python-tooling/actions/workflows/pages/pages-build-deployment) but **_our_** action, which [builds and deploys is fine](https://github.com/UCL-ARC/python-tooling/deployments).

**Comment by samcunliffe** [comment]
<img width="726" alt="Screenshot 2023-07-26 at 15 46 55" src="https://github.com/UCL-ARC/python-tooling/assets/1836192/6c8c3cfe-d961-4ec6-834e-fde3a5393d2d">

Weird. I don't understand. The action we made yesterday is fine and the settings correctly realises that that's what we're doing. So I'm confused by the extra workflow in the actions tab.

**Comment by samcunliffe** [comment]
Rubberduck @dpshelio helped. Probs OK now. Need a new commit on `main` before I can confirm.
Hopefully fixed in settings.

**Comment by paddyroddy** [comment]
Could be related to the changes from Ben Thomas

**Comment by samcunliffe** [comment]
Looks like it was a v. minor misconfigured setting.
Now we have sane builds and that weird guy didn't run for 6ca79c92be6c08c462b0c49770bbd1b1460c546a

👍
