### ISSUE TITLE
Publishing packages in conda-forge

### ISSUE THREAD

**Issue by mxochicale** [UCL-ARC/python-tooling#132]
To follow up the creation of steps to generate conda-forge package. 
_Originally posted by @paddyroddy in https://github.com/UCL-ARC/python-tooling/issues/110#issuecomment-1650121748_

**Comment by dstansby** [comment]
I think we can recommend using https://github.com/conda/grayskull for this

**Comment by paddyroddy** [comment]
I _think_ @mxochicale means adding CI for this. Although, I'm not sure this is worth doing.

**Comment by dstansby** [comment]
I don't think you can add CI to do it, don't you have to go through creating a conda-forge feedstock and doing it on their organisation?

**Comment by paddyroddy** [comment]
Yeah exactly, which is why I don't think it is worth doing

**Comment by dstansby** [comment]
👍 I'll close this then
