### ISSUE TITLE
licence versus license

### ISSUE THREAD

**Issue by matt-graham** [UCL-ARC/python-tooling#158]
We currently are using both license and licence in different places to refer to the same thing. 

https://github.com/UCL-ARC/python-tooling/blob/2be493a143a5bdc81121f8c5003e9a3b857a9027/%7B%7Bcookiecutter.project_slug%7D%7D/LICENCE.md?plain=1#L1

https://github.com/UCL-ARC/python-tooling/blob/2be493a143a5bdc81121f8c5003e9a3b857a9027/%7B%7Bcookiecutter.project_slug%7D%7D/LICENCE.md?plain=1#L3

'licence' is arguably 'more correct' in British English I think as we are using as a noun rather than verb, while in American English both noun and verb are spelt 'license' however on GitHub more generally license is much more common and the `LICENSE` file for this repository uses that spelling, as does the sidebar information even if there is a `LICENCE` / `LICENCE.md` file present.

In my opinion would probably be better to just standardize on license as using both is a bit confusing.

**Comment by paddyroddy** [comment]
I agree we should standardise. When I started this I put `licence` 😁 but I guess others didn't look

**Comment by samcunliffe** [comment]
I went with 🇬🇧 in https://github.com/UCL-ARC/python-tooling/pull/26
Didn't change the spelling of the licences themselves though.

**Comment by samcunliffe** [comment]
Ah yeah I remember. We went for 🇬🇧 wherever possible. So filenames yes, but I guess sidebar: no (since out of our control). 

If I change to 'licence' in the licenses... [it seems GH still recognises it](https://github.com/samcunliffe/licence-test).

**Comment by samcunliffe** [comment]
> Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

GPL won't allow it though.

**Comment by matt-graham** [comment]
Possible resolutions seem to be

1. Do nothing and leave as what we have at the moment (licence in file and variable names, license in licen[c|s]e text)
2. Standardize on license everywhere

Changing to licence eveywhere doesn't seem to be an option due to @samcunliffe's point about GPL text needing to be reproduced verbatim above.

I would favour 2 but if consensus is on 1 happy to just close this.
