### ISSUE TITLE
Automatically bump pre-commit hook versions

### ISSUE THREAD

**Issue by p-j-smith** [UCL-ARC/python-tooling#17]
Some of the pre-commit hooks (e.g. ruff) have newer versions

We could use something like [pre-commit.ci](https://pre-commit.ci/) or [renovate](https://github.com/renovatebot/renovate) to automatically keep the versions up to date?

**Comment by paddyroddy** [comment]
I'd rule out `pre-commit.ci` as it isn't free for private repos - which our consumers might have!

**Comment by p-j-smith** [comment]
what do you think about running a cron job and [this reusable workflow](https://github.com/browniebroke/github-actions/blob/main/.github/workflows/pre-commit-autoupdate.yml) to check for updates and submit prs? [Here's an example](https://github.com/browniebroke/github-actions#pre-commit-auto-update) of how to use it. Or is there a different way you'd recommend?

**Comment by paddyroddy** [comment]
Can you check those links? First one doesn't work for me.

**Comment by paddyroddy** [comment]
I like the idea of renovate.

**Comment by p-j-smith** [comment]
> Can you check those links? First one doesn't work for me.

woops sorry, I've fixed it now

**Comment by paddyroddy** [comment]
I would just say let's configure `renovate` to pick up `pre-commit` versions. I'd find this useful for my own stuff too!

**Comment by paddyroddy** [comment]
https://docs.renovatebot.com/modules/manager/pre-commit#enabling

**Comment by samcunliffe** [comment]
How long should we expect to wait for @renovatebot to send us a PR?
