### ISSUE TITLE
Update documentation tooling recommendations

### ISSUE THREAD

**Issue by matt-graham** [UCL-ARC/python-tooling#187]
@paddyroddy and I think we should maybe switch to recommending both Mkdocs and Sphinx as 🟢 as they seem to offer similar level of functionality / extensions and both are mature / well used.

**Comment by p-j-smith** [comment]
Yeah I agree, I used Mkdocs for the first time recently and really like it. I would probably even suggest using it over Sphinx if someone is not familiar with either of them

**Comment by paddyroddy** [comment]
Yeah, I would actually play `MkDocs` way ahead of `sphinx`. Most people's views on `sphinx` come from the fact that it is much more mature, and comparisons are largely from when `MkDocs` was in its infancy. I think we should make our cookie docs in #115 in `MkDocs` personally.

**Comment by matt-graham** [comment]
I don't have strong opinions favouring Sphinx, but I think _much more mature_ is a valid reason to favour one tool over another for a default recommendation. Sphinx has more regular contributors than MkDocs and is more widely used, so I'd say it's less at risk of becoming non-maintained. For generating API documentation `autodoc` is a built-in extension in Sphinx, while `mkdocstrings` is a relatively young project and most of development seems to be by one main contributor. There is some [interesting related discussion here](https://github.com/encode/httpx/discussions/1220). I'd personally err towards recommending both with an explanation of something like

> Sphinx is the de-facto standard that is widely used. It is well tested, reliable and very customisable. 
> Mkdocs is a more recent but still relatively mature documentation system that can be simpler to set up than Sphinx.
