### ISSUE TITLE
Nice way to pull the corresponding license.

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/python-tooling#19]
[The cookiecutter examples](https://cookiecutter.readthedocs.io/en/stable/advanced/choice_variables.html) seem to recommend a giant if clause in LICENSE.

Not sure this is the smartest way, and it feels like there's probably a better solution.

**Comment by samcunliffe** [comment]
* Appropriate classifier needs to be in pyproject.toml
* Should probably use "licence" 🇬🇧 unless _explicitly_ required to use the US spelling.

**Comment by paddyroddy** [comment]
Fixed in #26.
