### ISSUE TITLE
Document next steps for the user once they run the tool

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#205]
@samcunliffe thought it would be good to say things like:
- Create `conda` environment
- Enter `conda environment`
- `pip install -e .` package
- Run `pre-commit install`
- etc.

**Comment by paddyroddy** [comment]
- code of conduct
- contributing guidelines
- etc.

**Comment by matt-graham** [comment]
Would also be worth mentioning steps for setting up deployment of documentation to GitHub Pages is user selected `deploy_docs_to_github_pages` option as discussed in #319.
