### ISSUE TITLE
Consistency between `{{ cookiecutter.x }}` and `{{cookiecutter.x}}`

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#215]
Not a big problem, but annoys me and may lead to bugs

**Comment by samcunliffe** [comment]
```
➤ git grep '{{cookiecutter' | wc -l
      22
➤ git grep '{{ cookiecutter' | wc -l
      15
```

Looks like no-space is winning.

**Comment by paddyroddy** [comment]
> Looks like no-space is winning.

I've since noticed that sometimes only one of these will work. Think this was when I was doing the `hooks`. But I can't remember why!

**Comment by samcunliffe** [comment]
Y U not closed?

## Reached via 
* #218

**Comment by samcunliffe** [comment]
[Sorry for the noise]

**Comment by paddyroddy** [comment]
> [Sorry for the noise]

Lol
