### ISSUE TITLE
Add CITATION.cff

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/python-tooling#22]
Should be able to split `cookiecutter.full_name` to grab the first name and surname for CITATION.cff.
Introduced in the history of #3 but that was broken.

* Can we have multiple authors in cookie-cutter templates?
* Remove citation section from README?

**Comment by matt-graham** [comment]
I tried investigating a bit whether we can have multiple author names in the `cookiecutter.json` file. 

In the latest dev version of cookieninja there is support for [dependent questions](https://cookieninja.readthedocs.io/en/latest/advanced/dependent_questions.html) which would allow us to do something like

```json
  "author_1_name": "UCL ARC",
  "author_1_email": "temp@gmail.com",
  "author_2_name": "",
  "author_2_email?{{cookiecutter.author_2_name != ''}}": "",
  "author_3_name?{{cookiecutter.author_2_name != ''}}": "",
  "author_3_email?{{cookiecutter.author_3_name != ''}}": "",
  "author_4_name?{{cookiecutter.author_3_name != ''}}": "",
  "author_4_email?{{cookiecutter.author_4_name != ''}}": "",
```

which would mean that the questions for `author_2_email` and so on would only appear if the previous questions haven't been left as the default empty string response.  We could then use this in the README file for example something like

```
{{cookiecutter.author_name_1}} ([{{cookiecutter.author_email_1}}](mailto:{{cookiecutter.author_email_1}}))
{%- if cookiecutter.author_name_2 != ''-%}
{{cookiecutter.author_name_2}} ([{{cookiecutter.author_email_2}}](mailto:{{cookiecutter.author_email_2}}))
{% endif %}
{%- if cookiecutter.author_name_3 != '' -%}
{{cookiecutter.author_name_3}} ([{{cookiecutter.author_email_3}}](mailto:{{cookiecutter.author_email_3}}))
{% endif %}
{%- if cookiecutter.author_name_4 != '' -%}
{{cookiecutter.author_name_4}} ([{{cookiecutter.author_email_4}}](mailto:{{cookiecutter.author_email_4}}))
{% endif %}
```

Unfortunately this feature was [only merged in to cookieninja after the last 1.0 release](https://github.com/cookieninja-generator/cookieninja/pull/26).

We could alternatively just allow for `author_name` and `author_email` to be passed comma delimited lists of names and emails and then manually split but this would have the issue of needing to ensure the two lists are aligned and being non-obvious from the prompt that this is supported.

**Comment by matt-graham** [comment]
As we're switching back to Cookiecutter (#186), dependent prompts route seems a non-starter.

That still leaves option of delimited lists for `author_name` and `author_email`, possibly changing to `author_names` and `author_emails` to signpost that multiple can be passed. There is then still some ambiguity over how to split a name in to family and given names given variety of name ordering conventions.

As a first pass maybe we just stick with single author + templated `CITATION.cff` and leave the multiple author question to a different issue.

**Comment by p-j-smith** [comment]
[Support for dependent questions in cookiecutter](https://github.com/cookiecutter/cookiecutter/pull/1762) is marked for release in 3.0, which apparently is [due on 11/11](https://github.com/cookiecutter/cookiecutter/milestone/28) (no idea how realistic that is though, only 1/11 issues for 3.0 are closed).

> As a first pass maybe we just stick with single author + templated CITATION.cff and leave the multiple author question to a different issue.

yeah this might be easiest for now
