### ISSUE TITLE
Now that she's leaving us, does @sfmig still want to be assigned all `Renovate`-related PRs?

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#241]
😭

**Comment by sfmig** [comment]
probs not, but I plan to still attend the sessions 😬

**Comment by paddyroddy** [comment]
> probs not, but I plan to still attend the sessions 😬

Your wish is my command

**Comment by sfmig** [comment]
> Your wish is my command

ah if only!
