### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#244]
To this repo & template. I have some here https://github.com/paddyroddy/python-template/tree/main/.github/ISSUE_TEMPLATE

**Comment by paddyroddy** [comment]
Fixed in #262

**Comment by dstansby** [comment]
🤔 I'm not seeing any template when I try and open a new issue, just the usual empty title and text boxes

**Comment by paddyroddy** [comment]
> 🤔 I'm not seeing any template when I try and open a new issue, just the usual empty title and text boxes

Hmm... me neither
