### ISSUE TITLE
Add other standard doc stuff

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#245]
Related to #240. Things like
- contributing guidelines
- code of conduct
- etc.

I have some of these here https://github.com/paddyroddy/python-template

**Comment by samcunliffe** [comment]
+1 for CONTRIBUTING.md

We can pull out the developer stuff from README and put it after a nice welcoming 

> "hi, please chat in discussions and don't be shy about opening issues"

(Exact phrasing subject to refinement)

**Comment by samcunliffe** [comment]
![Screenshot 2024-01-22 at 16 33 46](https://github.com/UCL-ARC/python-tooling/assets/1836192/b70d955b-60fc-4bf9-8061-c170422059c5)

**Comment by paddyroddy** [comment]
- [x] code of conduct #247 
- [x] contributing #252
- [x] issue templates #262 

I'm not really a fan of PR templates. Anyone have strong views?

**Comment by samcunliffe** [comment]
Also not a fan of PR templates, so with two 👎 , I claim this is done.
