### ISSUE TITLE
Add pytest-benchmarking as a red guy with justification.

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/python-tooling#251]

**Comment by samcunliffe** [comment]
Adding help wanted because I don't remember the justification for this. (Docathon from January?)
@paddyroddy ? You remember?

**Comment by paddyroddy** [comment]
Sorry I don't. I believe @sfmig was actively benchmarking at the time, though.

**Comment by sfmig** [comment]
I don't remember this discussion or deciding to set it red.... (maybe @dstansby does?)

From my notes when I was working on benchmarking brainglobe workflows, I have:
> [pytest-benchmark plugin](https://pypi.org/project/pytest-benchmark/) ---> nice that it integrates with pytest but seems a bit limited? (mostly aiming to benchmark a function)

They also mention this function focus on their [docs](https://github.com/ionelmc/pytest-benchmark#examples). I don't remember having strong opinions to set it to red though... 🤔. FYI this is [an example repo](https://github.com/python-attrs/cattrs/blob/main/bench/test_attrs_collections.py) where they use it.

**Comment by dstansby** [comment]
Sorry, I can't remember ever trying pytest-benchmark. Maybe we just close this issue and if someone wants to add pytest-benchmark after using it at a later date they can?
