### ISSUE TITLE
Add to jupyter notebooks page

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/python-tooling#258]
* Add mention of the VSCode plugin.
* Add a section about live environments:
   *  binder
   * Google collab
   * GH Codespaces
   * Coolcalc which UCL has a subscription for...  @dpshelio ?

**Comment by mxochicale** [comment]
Closing this one for now. 

I didn't include [Coolcalc](https://docs.coolcalc.com/index.html) as I don't see anything that use jupyter notebooks but feel free to re-open it.

**Comment by dpshelio** [comment]
I think that's not Coocalc but [Cocalc](https://cocalc.com/) what probably @samcunliffe wanted to link to.
At UCL is only used within teaching, and licences are requested course-by-course basis.
They have been providing it a really collaborative Jupyter environment for a while. Would you like me to add info to the file?

**Comment by samcunliffe** [comment]
Yeah sorry, this is me writing minutes for something that was said in real life and not getting the name right.

It should go in, sure. It sounds like it's a) really good but b) not open source/free/usable for research projects(?) so probably it's ... 🔴 ?

**Comment by samcunliffe** [comment]
@dpshelio @paddyroddy I think we can actually re-close this...

We currently have most of this issue [done as-written](https://github.com/UCL-ARC/python-tooling/blob/main/docs/pages/libraries/jupyter-notebooks.md).

Do we want a final tweak to the language to clarify that `ruff` works out of the box... because that page mentions `nbqa black` but not `ruff`.

**Comment by paddyroddy** [comment]
Agree, I think we should close
