### ISSUE TITLE
Add some reference docs on all the cookiecutter options

### ISSUE THREAD

**Issue by dstansby** [UCL-ARC/python-tooling#296]
### Which Section of the Documentation Needs Improving?

It's wasn't clear from just the `cookiecutter` command line what `initialise_git_repository` does. In particular, does it initialise the repo locally or put it on GitHub? Or neither? In general it would be good to have some reference docs on what each of the cookiecutter optiolns is used for or does.

### What Can be Improved About This Section

I think some reference documentation on what each of the cookicutter options means/is used for would be nice.

**Comment by paddyroddy** [comment]
It doesn't create a GitHub repository! I decided against that as too many nuances. It does things like recommending the `GitHub CLI` call, or just point to the documentation. Have another look at the hook.

**Comment by dstansby** [comment]
Woops, I got confused. Either way it would be nice to have some reference documentation (even if it's short) about each of the options in the cookiecutter template explaining what they're used for, or what they do (which would have saved my confusion 😄 ).

**Comment by dstansby** [comment]
I updated the title and body of the issue to reflect the comment above ☝️

**Comment by paddyroddy** [comment]
Yeah, I like that idea

**Comment by samcunliffe** [comment]
Should the options docs just go in the body of README.md?

Perhaps in a `<details>` (I do love me a details).

```
<details><summary>Click to see more information about the questions...</summary>

* `github_owner`: either your GitHub username or the name of the GitHub organisation you're creating the repository under.
* `initialise_git_repository`: runs `git init`... insert nuance here.

<details>
```

**Comment by matt-graham** [comment]
As an alternative or complement to having the options documented separately in the README or similar, `cookiecutter` supports having [human-readable prompts in place of the variable names](https://cookiecutter.readthedocs.io/en/stable/advanced/human_readable_prompts.html) which would at least allow us to decouple the variable names and what is shown to the user.
