### ISSUE TITLE
Remove mentions of mamba?

### ISSUE THREAD

**Issue by dstansby** [UCL-ARC/python-tooling#301]
[libmamba is now the default solver for conda](https://conda.org/blog/2023-11-06-conda-23-10-0-release/), so to keep things simple it might be worth removing mentions of mamba from the docs here?

**Comment by paddyroddy** [comment]
I'm pretty sure we discussed this at the last session. But I can't remember what the consensus was.

**Comment by samcunliffe** [comment]
Yeah it's a task on https://github.com/UCL-ARC/python-tooling/issues/257 ~~(which we didn't get to).~~

Sorry, I'm wrong:  it's in review in #265.
