### ISSUE TITLE
Implement some kind of `logging`

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#304]
Either something like this https://github.com/astro-informatics/sleplet/blob/6418525d4f8bb0b521205d5c2471125ac3172cde/src/sleplet/__init__.py#L30-L40 or a package which does the same thing

**Comment by samcunliffe** [comment]
If you mean putting this in the 🍪 template, I'm actually 👎 for this.
Where do we stop with package recommendations?

A webpage of good utility libraries (logging, CLI, parallel processing, async...) is not a bad idea. But we should collect the things that the group is currently using and rank them first.

For example [typer](https://typer.tiangolo.com/#run-it) is great. But there are some arguments for using [click](https://click.palletsprojects.com/) directly or even sticking with ArgParse. I probably wouldn't force a decision on the template users. (I know less about logging.)

**Comment by paddyroddy** [comment]
I meant in the `__init__.py` which is the standard convention

**Comment by samcunliffe** [comment]
But you're still making a choice for them. Standard? loguru? My claim is that we should stop at infrastructure.

**Comment by paddyroddy** [comment]
Discouraging use of `print` is still a win

**Comment by dstansby** [comment]
Would definitely be nice to have a page on logging (partly so I could learn something myself!).

I think I'm +/- 0 on having a logger by default in the package. For some uses it's fine having `print()` statments, and it would be annoying to have to remove any logger configuration and dependencies. For example, I'm currently using a package that isn't intended to be used outside my research group or be a dependency of anything, so to keep things simple I've just stuck in `print` statments where needed.
