### ISSUE TITLE
Markdown link checker?

### ISSUE THREAD

**Issue by sfmig** [UCL-ARC/python-tooling#310]
### What is the Topic of Your Question

Pre-commit hooks

### Add Your Question Below

Should we add a pre-commit hook that checks links are alive in markdown files?

Something like [this](https://github.com/tcort/markdown-link-check).

I found it useful recently 😬

**Comment by paddyroddy** [comment]
Not saying we shouldn't, but we already have link checking in CI https://github.com/UCL-ARC/python-tooling/blob/main/.github/workflows/links.yml (which is quite flaky)

**Comment by dstansby** [comment]
I think having a link checker would generate too many false negatives (e.g. when a website happens to be down) to be used in a pre-commit hook, which is run on every commit. How about adding a tox environment that runs a link check? That way it would be easy to run it manually occasionally.

**Comment by paddyroddy** [comment]
I don't think we need both, we have it in CI. Considering flakiness is expected, I think just having CI (which can be re-run) should be enough.

**Comment by sfmig** [comment]
CI only sounds good!

**Comment by paddyroddy** [comment]
Thanks for the suggestion @sfmig, closing 🦀
