### ISSUE TITLE
Add section to docs on GUI toolkits

### ISSUE THREAD

**Issue by dstansby** [UCL-ARC/python-tooling#354]
### Is Your Feature Request Related to a Problem? Please Describe

n/a

### Describe the Solution You'd Like

A seciton in the docs on toolkits for making GUIs with Python.

**Comment by p-j-smith** [comment]
Any thoughts on which toolkits to include / recommend? Some we could include:

- [QtPy](https://github.com/spyder-ide/qtpy)
- [PySide6](https://wiki.qt.io/Qt_for_Python)
- [magicgui](https://github.com/pyapp-kit/magicgui)

Plus more application-specific ones:

- [napari](https://github.com/napari/napari)
- [PyVistaQt](https://github.com/pyvista/pyvistaqt)
- [Trame](https://github.com/Kitware/trame) (a web framework for VTK but can also be used to create apps that run locally in the browser)

And should we include packages for creating applications (perhaps that should be a separate section though):

- [PyInstaller](https://github.com/pyinstaller/pyinstaller)
- [pyapp](https://github.com/pyapp-org/pyapp)

**Comment by samcunliffe** [comment]
* [PyQt](https://wiki.python.org/moin/PyQt) vs PySide vs [QtPy](https://pypi.org/project/QtPy/)
  > QtPy is a small abstraction layer that lets you write applications using a single API call to either PyQt or PySide.
  >
  > It provides support for PyQt5, PySide2, PyQt6 and PySide6 using the Qt5 layout (where the QtGui module has been split into QtGui and QtWidgets).

**Comment by p-j-smith** [comment]
> QtPy is a small abstraction layer that lets you write applications using a single API call to either PyQt or PySide.
> 
> It provides support for PyQt5, PySide2, PyQt6 and PySide6 using the Qt5 layout (where the QtGui module has been split into QtGui and QtWidgets).

Yep, QtPy is the way to go you're e.g. developing an app with a plugin system (so other's can choose which Qt bindings to use), or if you're developing a widget that others can use in their apps.

But if you're developing an app that you'll build with PyInstaller/pyapp and distribute as an executable, there might be no need to support multiple bindings and you could choose to use PySide6 directly (or any other bindings). Although I would probably avoid using PyQt over PySide - PyQt has a more restrictive license, PySide is developed by Qt, and the PySide docs are (nowadays) better than the PyQt docs
