### ISSUE TITLE
Create separate page with packages for creating CLIs

### ISSUE THREAD

**Issue by p-j-smith** [UCL-ARC/python-tooling#355]
### Is Your Feature Request Related to a Problem? Please Describe

n/a

### Describe the Solution You'd Like

A section in the docs on packages for creating CLIs with Python. Could include:

- [argparse](https://docs.python.org/3/library/argparse.html)
- [click](https://github.com/pallets/click)
- [typer](https://github.com/tiangolo/typer)

**Comment by samcunliffe** [comment]
[Already done?](https://github-pages.arc.ucl.ac.uk/python-tooling/pages/utilities.html#command-line-interface)

**Comment by paddyroddy** [comment]
![image](https://github.com/UCL-ARC/python-tooling/assets/15052188/ae96977b-4f32-4ea5-82f4-021d6e636c93)

**Comment by samcunliffe** [comment]
It probably means that the title of the page is not great.
If we're going to add a list of library recommendations: perhaps it should just be "Libraries"?

**Comment by dstansby** [comment]
I'd be pro putting CLI libraries on to their own page, so I will re-open this.

**Comment by p-j-smith** [comment]
Ooops! Should have actually read the docs. But yeah, +1 on a separate page for CLIs, and for renaming `Utility libraries`

**Comment by samcunliffe** [comment]
I _think_ I vote to rename "Utility Libraries" → "Libraries" or "Libraries we recommend" but! keep a long list of them all there (alphabetised: API libraries, CLI libraries, GUI...). Since libraries aren't really tooling I don't think I would expect each category of library to have its own page.

Not a strong opinion though.

**Comment by p-j-smith** [comment]
> I think I vote to rename "Utility Libraries" → "Libraries" or "Libraries we recommend" but! keep a long list of them all there (alphabetised: API libraries, CLI libraries, GUI...). Since libraries aren't really tooling I don't think I would expect each category of library to have its own page.

Yep that sounds sensible
