### ISSUE TITLE
Links not rendered correctly in Documentation page on website

### ISSUE THREAD

**Issue by giordano** [UCL-ARC/python-tooling#361]
### Which Section of the Documentation Needs Improving?

Some links in https://github-pages.arc.ucl.ac.uk/python-tooling/pages/docs.html#documentation aren't rendered correctly

### What Can be Improved About This Section

https://github.com/UCL-ARC/python-tooling/blob/b2454d7ae211d40e497a39b2adc4f33437814ec0/docs/pages/docs.md#L16-L26  I believe this was broken by #356.

**Comment by paddyroddy** [comment]
Thanks, looks like https://github.com/prettier/prettier/issues/9232 is why

**Comment by paddyroddy** [comment]
Not a problem with the other markdown link format

**Comment by paddyroddy** [comment]
And not problem on GitHub, only on the website

**Comment by paddyroddy** [comment]
Looks like I can fix it with https://github.com/github/jekyll-commonmark-ghpages, but that has it's downsides so will revert (manually)
