### ISSUE TITLE
Print out details of how to configure repository to allow deploying docs in `post_gen_project.py` hook

### ISSUE THREAD

**Issue by matt-graham** [UCL-ARC/python-tooling#391]
### Is Your Feature Request Related to a Problem? Please Describe

Currently if the `deploy_docs_to_github_pages` template option is set to `y` / `True` the documentation workflow will be set up to push the built documentation to a branch `gh-pages` to allow deploying on GitHub Pages however we only document that additional steps are required to get this working this in a comment in the workflow. Specifically the repository needs to be configured in `https://github.com/{{owner}}/{{project_slug}/settings/pages` to deploy GitHub Pages from the branch `gh-pages` (which will be created after first run of documentation workflow on push to `main`) and (which is not currently documented) the permissions for GitHub Actions workflows need to be changed for the repository to `Read and write permissions` in `https://github.com/{{owner}}/{{project_slug}/settings/actions`.

### Describe the Solution You'd Like

- Build on the current implementation of the `post_gen_project`  hook which deals with the `initialise_empty_git_repository` template option to also output instructions to the user to update repository settings as above if `deploy_docs_to_github_pages` is set to `True`.

### Describe Alternatives You've Considered

#205 suggests documenting next steps such as this - I'm assuming this means in the repository README? I think that would also be good to have but I think having something similar to the behaviour for `initialise_empty_git_repository` would be good.

**Comment by paddyroddy** [comment]
#205 was just meant to be in some way, currently there's a fair bit we assume
