### ISSUE TITLE
Default to enabling deploying docs to GitHub pages in template

### ISSUE THREAD

**Issue by matt-graham** [UCL-ARC/python-tooling#408]
### Is Your Feature Request Related to a Problem? Please Describe

With #404 now merged in the user gets relatively clear instructions on next steps needed to get deployment of HTML documentation to GitHub Pages working if `deploy_docs_to_github_pages` option is set to `True`, so I would argue it would make sense to now have this option set to `True` by default, as if a user does not have a strong preference otherwise (for example wanting to use another hosting solution like ReadTheDocs) I think defaulting to encouraging having documentation hosted somewhere would be good. However I realise this might be contentious so wanting to get opinions on this - @paddyroddy, @samcunliffe, @dstansby.

### Describe the Solution You'd Like

Changing default for cookiecutter option `deploy_docs_to_github_pages` to `True`. 

### Describe Alternatives You've Considered

Leaving default as is.

**Comment by dstansby** [comment]
👍 from me

**Comment by paddyroddy** [comment]
I agree, setting up `readthedocs` is another barrier to entry and for beginner users getting (/forcing) them to have documentation is great
