### ISSUE TITLE
Add recommendations on GitHub branch protection rules and/or a ruleset recipe to template

### ISSUE THREAD

**Issue by matt-graham** [UCL-ARC/python-tooling#417]
### Is Your Feature Request Related to a Problem? Please Describe

@zmek who attended the _Festival of Digital Research and Scholarship_ workshop asked about recommendations for setting up rulesets to protect `main` branch with regards to the [tutorial](https://hackmd.io/@matt-graham/Byvn9LkS0) we used there.

### Describe the Solution You'd Like

I think having some recommendations around a good basic default branch protection rule might be useful (possibly require status checks + pull requests before merging?) and/or creating a ruleset JSON file similar to those in the `ruleset-recipes` repository Zella linked to that people could import to set up a minimal set of rules.

**Comment by paddyroddy** [comment]
This might be possible via the GitHub CLI? I think we could detect a presence of CLI and a do a lot of extra automated things

**Comment by matt-graham** [comment]
I had a look yesterday and it doesn't look like its currently possible to add / edit rulesets [only view them](https://cli.github.com/manual/gh_ruleset) and similarly doesn't seem to be any relevant options [under `gh repo edit` subcommand](https://cli.github.com/manual/gh_repo_edit).

**Comment by paddyroddy** [comment]
> I had a look yesterday and it doesn't look like its currently possible to add / edit rulesets [only view them](https://cli.github.com/manual/gh_ruleset) and similarly doesn't seem to be any relevant options [under `gh repo edit` subcommand](https://cli.github.com/manual/gh_repo_edit).

That's a shame. If nothing else, we can have JSON files that they could import.

**Comment by dstansby** [comment]
I'd say this is out of context for this project, as it's not Python package specific. Perhaps a separate `UCL-ARC/github-tooling` repo would work for this instaed?

**Comment by paddyroddy** [comment]
> I'd say this is out of context for this project, as it's not Python package specific. Perhaps a separate `UCL-ARC/github-tooling` repo would work for this instaed?

I think something I noted from the workshops last week. People who were there knew `Python`, but weren't very familiar with everything else. So I do actually think there's merit in doing this.

**Comment by dstansby** [comment]
👍 agree there's merit, but still think it's outside the scope of this repo.

**Comment by dstansby** [comment]
I'm still on the side of this is out of scope (but maybe nice to have in a "git-tooling" or "github-tooling" repo?). Unless anyone disagrees, I'll close this issue in a couple of weeks

**Comment by samcunliffe** [comment]
Falls under the scope of a proposed extension to the [UCL-ARC/coding-standards](https://github.com/UCL-ARC/coding-standards).

So I think this can actually be closed immediately. We can reopen if they don't end up adding anything there.
