### ISSUE TITLE
Merge queues

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/python-tooling#42]
# Feature request

To the project admin to set up [merge queue](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue#about-merge-queues) rule.

**Comment by dstansby** [comment]
Is this a request to enable the merge queue on this repository?

**Comment by samcunliffe** [comment]
I'm less convinced by merge queues. We have a "merge when checks pass" button which is good enough for me.

**Comment by paddyroddy** [comment]
> I'm less convinced by merge queues. We have a "merge when checks pass" button which is good enough for me.

I like this button
