### ISSUE TITLE
We should recommend hypothesis for testing

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#426]
### Is Your Feature Request Related to a Problem? Please Describe

Have used it myself in the past https://github.com/astro-informatics/sleplet/blob/8910cd56c3bb39edb265184f78a7c743b1ffff20/tests/test_translation.py#L22-L41, but have just learnt about the [ghostwriting](https://hypothesis.readthedocs.io/en/latest/ghostwriter.html) feature which writes tests for you! Super cool.

### Describe the Solution You'd Like

We should document `hypothesis` with a traffic light symbol

**Comment by dstansby** [comment]
👍 I've used it before, found it to be very helpful and with great docs so I think should go in as a 🟢

**Comment by samcunliffe** [comment]
Fixed via #467
