### ISSUE TITLE
Move all non-tooling libraries into a `Recommended libraries` page

### ISSUE THREAD

**Issue by p-j-smith** [UCL-ARC/python-tooling#427]
### Which Section of the Documentation Needs Improving?

The pages on libraries we recommended for non-tooling purposes (e.g. GUIs, CLIs, etc.)

### What Can be Improved About This Section

Clearer organisation of recommended libraries

### How to Improve This Section

Rename `Utility libraries` to `Recommended libraries` (as suggested in https://github.com/UCL-ARC/python-tooling/issues/355#issuecomment-2069093754).

Move the GUI libraries page (added in #373) into `Recommended libraries`.

What other pages, if any should be moved? [Parallel and asychronous processing](https://github-pages.arc.ucl.ac.uk/python-tooling/pages/parallel-async.html)?

**Comment by dstansby** [comment]
Hmm, I still remain unconvinced by this 😄 - perhaps a definition of tooling vs non-tooling would help me get on board with this change?

To be honest I think splitting the "Utility libraries" page up into three more (CLI, GUI, Logging) would be nicer and make what's currently there more discoverable. I worry that having a generic "Recommended libraries" reduces discoverability of the tools from the home page, because "libraries" is a very generic catch-all term.

**Comment by samcunliffe** [comment]
> perhaps a definition of tooling vs non-tooling

In my head it's something like:

"Tooling" == { tools that are executables, linters, infrastructure things like GitHub actions, doc build systems, `pytest`, `pytest` plugins, ...}. These things are more-or-less universal: to first order every project will want these.

"Non tooling" == python packages that you might add to your dependencies but that are project-dependent. Not every project will want these. 

e.g. If you're making an API: you would have a significant dependency on -- say-- fastapi. But not every project should have a fastapi dependency (and it shouldn't therefore be in the cookie-cutter template). And it's not a tool. But we might still want to recommend it.

**Comment by samcunliffe** [comment]
We could make use of the [Just-the-docs parent attribute](https://just-the-docs.com/docs/navigation-structure/#pages-with-children)? Does that make it better or worse?
Then it could be one page-per-theme and all libraries are under a subdirectory...

![Capture](https://github.com/user-attachments/assets/128bfb2a-7bae-4e7e-ab72-61191c7f20ce)

**Comment by dstansby** [comment]
👍 https://github.com/UCL-ARC/python-tooling/issues/427#issuecomment-2233271059 makes sense and clarifies it for me. And having the parent arrow thing in the comment above would fix my discoverability concern 👍
