### ISSUE TITLE
`venv` is not recommended, but no reason is given.

### ISSUE THREAD

**Issue by dpshelio** [UCL-ARC/python-tooling#446]
### Which Section of the Documentation Needs Improving?

[virtual environments](https://github-pages.arc.ucl.ac.uk/python-tooling/pages/virtual.html#virtual-environments)

### What Can be Improved About This Section

:red_circle: for `venv` is not explained, though on the main page, when [explaining the traffic light system](https://github-pages.arc.ucl.ac.uk/python-tooling/#traffic-lights) says (bold is mine):
> 🔴 We actively discourage using this. This could be because it’s no longer maintained, not open source, or difficult to use. Consider moving to alternatives if you’re currently using something that’s red. **A reason for not using this is given.**

### How to Improve This Section

I'd like to know the reason we said so, as it's what I normally recommend.

**Comment by samcunliffe** [comment]
My memory is hazy, but we recommended `virtualenv` above `venv` as `virtualenv` is interchangeable and `venv` [has fewer features whilst also being slower](https://virtualenv.pypa.io/en/latest/)...?

@ruaridhg can you remember any more? It looks like [you were tasked with making the virtual environments table](https://github.com/UCL-ARC/python-tooling/commit/65b383f020a656d42624f55e14706bfd2beb2014) back in the original website-only repo ([migrated here](https://github.com/UCL-ARC/python-tooling/pull/70)).

**Comment by ruaridhg** [comment]
> My memory is hazy, but we recommended `virtualenv` above `venv` as `virtualenv` is interchangeable and `venv` [has fewer features whilst also being slower](https://virtualenv.pypa.io/en/latest/)...?
> 
> @ruaridhg can you remember any more? It looks like [you were tasked with making the virtual environments table](https://github.com/UCL-ARC/python-tooling/commit/65b383f020a656d42624f55e14706bfd2beb2014) back in the original website-only repo ([migrated here](https://github.com/UCL-ARC/python-tooling/pull/70)).

Also struggling to remember anything additional. I think it was more not recommended as a comparative recommendation since I don't think any of the 🔴 traffic light reasons apply to `venv`
