### ISSUE TITLE
Adopt native TOML `tox` support

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#455]
### Is Your Feature Request Related to a Problem? Please Describe

Following https://github.com/tox-dev/tox/issues/3353 https://github.com/ymyzk/tox-gh-actions/discussions/197, it will at some be possible to have full native TOML support. I tried this for now and couldn't get it to work, so we might need to wait a bit. This would involve removing the lecacy INI format.

**Comment by gaborbernat** [comment]
https://tox.wiki/en/4.21.0/config.html#pyproject-toml-native You should be able to do it all, in case you're running into problems, please feel free to tag me.

**Comment by gaborbernat** [comment]
> Following [tox-dev/tox#3353](https://github.com/tox-dev/tox/pull/3353) [ymyzk/tox-gh-actions#197](https://github.com/ymyzk/tox-gh-actions/discussions/197),

Any reason why not use https://github.com/tox-dev/tox-gh instead? 😆

**Comment by paddyroddy** [comment]
@gaborbernat I have made a start on this and using `tox-gh`. I'm unsure of how to port the `[gh]` in the `legacy_tox_ini` section to TOML, https://github.com/astro-informatics/sleplet/pull/421

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/tox-gh?tab=readme-ov-file#examples

**Comment by paddyroddy** [comment]
@gaborbernat got this working in #460 😄
