### ISSUE TITLE
Jupyter notebook formatting

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#49]
Wonder whether we could make them better in git using this https://github.com/nbQA-dev/nbQA in `pre-commit`

**Comment by p-j-smith** [comment]
I don't think we currently have any notebooks in the template? Or do you mean we should add this to the docs as a recommended tool?

**Comment by paddyroddy** [comment]
I meant in the `pre-commit` of the template as our users might have notebooks.

**Comment by samcunliffe** [comment]
Me and @krishnakumarg1984 (and @matt-graham ) have exactly this. We're supporting some researchers who are using Jupiter notebooks and we probably want to lint them without imposing **_too much_** of a workflow change. 

Some webpage recommendations (even if not included in the package template) would be appreciated.

We can probably repurpose this ticket for documenting what we learn. And/or add to the template pre-commit config as a final task, if we want that?

Some claims found whilst browsing:
* [`black[jupyter]` works](https://black.readthedocs.io/en/stable/getting_started.html#installation)
* [`ruff` works](https://beta.ruff.rs/docs/faq/#does-ruff-support-jupyter-notebooks), and integrates well with...
* [nbQA](https://github.com/nbQA-dev/nbQA) which also works as a [pre-commit tool](https://nbqa.readthedocs.io/en/latest/pre-commit.html#pre-commit).

**Comment by samcunliffe** [comment]
@paddyroddy do you still want this in the template? Or is documenting it enough?

**Comment by paddyroddy** [comment]
I would have thought `pre-commit` hooks? Worst case is adding a minor delay if not using them

**Comment by dstansby** [comment]
I think `ruff` does jupyter notebook formatting now, at least I've seen it happening in other repos.

**Comment by Saransh-cpp** [comment]
Yep, ruff does support formatting jupyter notebooks - https://docs.astral.sh/ruff/configuration/#jupyter-notebook-discovery

**Comment by samcunliffe** [comment]
I keep forgetting: did we say we were just going to have the notebooks page? Or do we want the template to actually provide a `will_your_project_use_notebooks` variable?

**Comment by paddyroddy** [comment]
> I keep forgetting: did we say we were just going to have the notebooks page? Or do we want the template to actually provide a `will_your_project_use_notebooks` variable?

Looks like there is a separate issue for this https://github.com/UCL-ARC/python-tooling/issues/258

**Comment by paddyroddy** [comment]
I'm going to close this as `ruff` now definitely supports notebook formatting (but didn't when this issue was raised)
