### ISSUE TITLE
@renovatebot bumping versions will break the regression test every time

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#503]
Are we sure we want this? Every time there's a new change, this test will have to be updated.

_Originally posted by @paddyroddy in https://github.com/UCL-ARC/python-tooling/pull/432#pullrequestreview-2384846831_

**Comment by dstansby** [comment]
Could we get rennovate to bump the version in the regression test data file at the same time?

**Comment by paddyroddy** [comment]
> Could we get rennovate to bump the version in the regression test data file at the same time?

So that was the hope. But it turns out there was a blocker. #505 fixes this.
