### ISSUE TITLE
Better/easier ways to contribute to the repo

### ISSUE THREAD

**Issue by mxochicale** [UCL-ARC/python-tooling#92]
Contributing to this repo via fork is a bit annoying than doing to what it is already suggested https://github.com/UCL-ARC/python-tooling/blob/main/README.md. Perhaps current contributors need to be added as writers or admins in this repo to help with PR reviews or add other potential contributors.

**Comment by paddyroddy** [comment]
Personally, I agree with @mxochicale. I can happily add you with `write` permissions

**Comment by samcunliffe** [comment]
All of @UCL-ARC/collaborations now has write.
Admins are @paddyroddy, @dstansby and ... me 😱 .

That's probably what we want for sensible collaboration vs. PoLP.
