### ISSUE TITLE
Start Planning page

### ISSUE THREAD

**Issue by mxochicale** [UCL-ARC/python-tooling#97]
The Python Template might come with a doc/requirements.rst file which is a good place to write up initial thoughts on what the library will or won't do. There are various planning elements and good practices for users to consider. Here some pointed that can be added in the planning page: 
* https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002802 
* https://github.com/lorensen/VTKExamples/blob/master/src/VTKBook/02Chapter2.md#22-goals-of-good-software-design
* https://en.wikipedia.org/wiki/Test-driven_development
* http://andtr.com/the-importance-of-software-requirements
* https://github.com/SciKit-Surgery/scikit-surgerytutorial02/blob/master/doc/04_Planning.rst

**Comment by samcunliffe** [comment]
Agreed. And now there's a place for that discussion .. https://github.com/UCL-ARC/coding-standards/issues/7

I'm going to take the liberty to close here and redirect opinions to Milan.
